language: node_js

sudo: false

node_js:
  - "5"

cache:
    directories:
        - node_modules

before_script:
  - cp .env.example .env

install:
  - travis_retry npm install

script:
  - gulp
  - npm run test
